# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d551c38276af975e8865971dd75d86d63c55d369ada5ed82f54ee807404b1b97e77946ce886ff64923815a862decf65fc6ae67382ce0073e22a97604c4b46608

test:
  secret_key_base: dc5fb613570e761a6ec606cd1ffa1eea700b08ce26615079a58870f111e72d1e6538a9ab7c02a53ec4930533d7707b2ccfdd948982b70ca7c0b47c992a1dbf31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
